[build]
  command = "npm ci && npm run build"
  publish = "dist/client"
  environment = { NODE_VERSION = "20" }

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]

[functions."*"]

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=()"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[headers]]
  for = "/*"

  [headers.values]
    Content-Security-Policy = "default-src 'self'; child-src 'self' https://s.tradingview.com https://www.tradingview.com; worker-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://s3.tradingview.com https://s.tradingview.com https://www.tradingview.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://s.tradingview.com https://www.tradingview.com; font-src 'self' https://fonts.gstatic.com https://s.tradingview.com https://www.tradingview.com; img-src 'self' data: blob: https://s3.tradingview.com https://s.tradingview.com https://www.tradingview.com; connect-src 'self' https://your-production-api.com https://s.tradingview.com https://www.tradingview.com https://api.tradingview.com https://widgetdata.tradingview.com wss://data.tradingview.com; frame-ancestors 'self'; frame-src 'self' https://s.tradingview.com https://www.tradingview.com; object-src 'none'; base-uri 'self'; form-action 'self'"

[[headers]]
  for = "/api/*"

  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self'; font-src 'self'; img-src 'self'; connect-src 'self' http://localhost:3001 https://your-production-api.com"
