import { lazyWithRetry } from '@/lib/performance'

// Lazy load all pages to reduce initial bundle size
export const AdvancedScreeningPage = lazyWithRetry(() => import('@/pages/AdvancedScreeningPage'), 'AdvancedScreeningPage')
export const AITestPage = lazyWithRetry(() => import('@/pages/AITestPage'), 'AITestPage')
export const CountryTestPage = lazyWithRetry(() => import('@/pages/CountryTestPage'), 'CountryTestPage')
export const AllBrokersPage = lazyWithRetry(() => import('@/pages/AllBrokersPage'), 'AllBrokersPage')
export const AuthorPage = lazyWithRetry(() => import('@/pages/AuthorPage'), 'AuthorPage')
export const BlogPage = lazyWithRetry(() => import('@/pages/BlogPage'), 'BlogPage')
export const BlogPostPage = lazyWithRetry(() => import('@/pages/BlogPostPage'), 'BlogPostPage')
export const BrokerDetailPage = lazyWithRetry(() => import('@/pages/BrokerDetailPage'), 'BrokerDetailPage')
export const BrokerDuelPage = lazyWithRetry(() => import('@/pages/BrokerDuelPage'), 'BrokerDuelPage')
export const BrokerFeesQuizPage = lazyWithRetry(() => import('@/pages/BrokerFeesQuizPage'), 'BrokerFeesQuizPage')
export const BrokerMatcherPage = lazyWithRetry(() => import('@/pages/BrokerMatcherPage'), 'BrokerMatcherPage')
export const BrokerPromotionsPage = lazyWithRetry(() => import('@/pages/BrokerPromotionsPage'), 'BrokerPromotionsPage')
export const CalculatorsPage = lazyWithRetry(() => import('@/pages/CalculatorsPage'), 'CalculatorsPage')
export const CandlestickPatternsQuizPage = lazyWithRetry(() => import('@/pages/CandlestickPatternsQuizPage'), 'CandlestickPatternsQuizPage')
export const CarryTradeQuizPage = lazyWithRetry(() => import('@/pages/CarryTradeQuizPage'), 'CarryTradeQuizPage')
export const CategoryPage = lazyWithRetry(() => import('@/pages/CategoryPage'), 'CategoryPage')
export const CentralBanksQuizPage = lazyWithRetry(() => import('@/pages/CentralBanksQuizPage'), 'CentralBanksQuizPage')
export const ChartingIntroQuizPage = lazyWithRetry(() => import('@/pages/ChartingIntroQuizPage'), 'ChartingIntroQuizPage')
export const ChartPatternsQuizPage = lazyWithRetry(() => import('@/pages/ChartPatternsQuizPage'), 'ChartPatternsQuizPage')
export const ComparePage = lazyWithRetry(() => import('@/pages/ComparePage'), 'ComparePage')
export const CostAnalyzerPage = lazyWithRetry(() => import('@/pages/CostAnalyzerPage'), 'CostAnalyzerPage')
export const CountriesPage = lazyWithRetry(() => import('@/pages/CountriesPage'), 'CountriesPage')
export const CurrencyPairsQuizPage = lazyWithRetry(() => import('@/pages/CurrencyPairsQuizPage'), 'CurrencyPairsQuizPage')
export const DashboardPage = lazyWithRetry(() => import('@/pages/DashboardPage'), 'DashboardPage')
export const SEOPage = lazyWithRetry(() => import('@/pages/SEOPage'), 'SEOPage')
export const DivergenceTradingQuizPage = lazyWithRetry(() => import('@/pages/DivergenceTradingQuizPage'), 'DivergenceTradingQuizPage')
export const EconomicCalendarPage = lazyWithRetry(() => import('@/pages/EconomicCalendarPage'), 'EconomicCalendarPage')
export const EconomicIndicatorsQuizPage = lazyWithRetry(() => import('@/pages/EconomicIndicatorsQuizPage'), 'EconomicIndicatorsQuizPage')
export const EducationHubPage = lazyWithRetry(() => import('@/pages/EducationHubPage'), 'EducationHubPage')
export const ElliottWaveQuizPage = lazyWithRetry(() => import('@/pages/ElliottWaveQuizPage'), 'ElliottWaveQuizPage')
export const FibonacciQuizPage = lazyWithRetry(() => import('@/pages/FibonacciQuizPage'), 'FibonacciQuizPage')
export const ForexBasicsQuizPage = lazyWithRetry(() => import('@/pages/ForexBasicsQuizPage'), 'ForexBasicsQuizPage')
export const ForexCorrelationQuizPage = lazyWithRetry(() => import('@/pages/ForexCorrelationQuizPage'), 'ForexCorrelationQuizPage')
export const ForexQuoteQuizPage = lazyWithRetry(() => import('@/pages/ForexQuoteQuizPage'), 'ForexQuoteQuizPage')
export const HarmonicPatternsQuizPage = lazyWithRetry(() => import('@/pages/HarmonicPatternsQuizPage'), 'HarmonicPatternsQuizPage')
export const HomePage = lazyWithRetry(() => import('@/pages/HomePage'), 'HomePage')
export const LeverageMarginQuizPage = lazyWithRetry(() => import('@/pages/LeverageMarginQuizPage'), 'LeverageMarginQuizPage')
export const LoginPage = lazyWithRetry(() => import('@/pages/LoginPage'), 'LoginPage')
export const LotSizesQuizPage = lazyWithRetry(() => import('@/pages/LotSizesQuizPage'), 'LotSizesQuizPage')
export const MarketAnalysisTypesQuizPage = lazyWithRetry(() => import('@/pages/MarketAnalysisTypesQuizPage'), 'MarketAnalysisTypesQuizPage')
export const MarketDataPage = lazyWithRetry(() => import('@/pages/MarketDataPage'), 'MarketDataPage')
export const MarketNewsPage = lazyWithRetry(() => import('@/pages/MarketNewsPage'), 'MarketNewsPage')
export const MethodologyPage = lazyWithRetry(() => import('@/pages/MethodologyPage'), 'MethodologyPage')
export const MovingAveragesQuizPage = lazyWithRetry(() => import('@/pages/MovingAveragesQuizPage'), 'MovingAveragesQuizPage')
export const NotFoundPage = lazyWithRetry(() => import('@/pages/NotFoundPage'), 'NotFoundPage')
export const OrderTypesQuizPage = lazyWithRetry(() => import('@/pages/OrderTypesQuizPage'), 'OrderTypesQuizPage')
export const PipQuizPage = lazyWithRetry(() => import('@/pages/PipQuizPage'), 'PipQuizPage')
export const QuizzesPage = lazyWithRetry(() => import('@/pages/QuizzesPage'), 'QuizzesPage')
export const RegisterPage = lazyWithRetry(() => import('@/pages/RegisterPage'), 'RegisterPage')
export const RiskManagementQuizPage = lazyWithRetry(() => import('@/pages/RiskManagementQuizPage'), 'RiskManagementQuizPage')
export const RsiIndicatorQuizPage = lazyWithRetry(() => import('@/pages/RsiIndicatorQuizPage'), 'RsiIndicatorQuizPage')
export const SourcesPage = lazyWithRetry(() => import('@/pages/SourcesPage'), 'SourcesPage')
export const SupportResistanceQuizPage = lazyWithRetry(() => import('@/pages/SupportResistanceQuizPage'), 'SupportResistanceQuizPage')
export const TradingJournalPage = lazyWithRetry(() => import('@/pages/TradingJournalPage'), 'TradingJournalPage')
export const TradingPsychologyQuizPage = lazyWithRetry(() => import('@/pages/TradingPsychologyQuizPage'), 'TradingPsychologyQuizPage')
export const WebinarsPage = lazyWithRetry(() => import('@/pages/WebinarsPage'), 'WebinarsPage')
export const DebugBrokersPage = lazyWithRetry(() => import('@/pages/DebugBrokersPage'), 'DebugBrokersPage')

// Best brokers pages
export const BestBrokersPage = lazyWithRetry(() => import('@/pages/BestBrokersPage'), 'BestBrokersPage')
export const BestBrokersCategoryPage = lazyWithRetry(() => import('@/pages/BestBrokersCategoryPage'), 'BestBrokersCategoryPage')
export const BestBrokersCountryPage = lazyWithRetry(() => import('@/pages/CountryPage'), 'BestBrokersCountryPage')

// Programmatic pages
export const ProgrammaticCategoryPage = lazyWithRetry(() => import('@/pages/best-brokers/[category]'), 'ProgrammaticCategoryPage')
export const ProgrammaticCountryPage = lazyWithRetry(() => import('@/pages/best-forex-brokers/[country]'), 'ProgrammaticCountryPage')
export const ProgrammaticSEOPage = lazyWithRetry(() => import('@/pages/brokers/[seoSlug]'), 'ProgrammaticSEOPage')

// Admin pages
export const AdminLogin = lazyWithRetry(() => import('@/pages/admin/AdminLogin'), 'AdminLogin')
export const AdminDashboard = lazyWithRetry(() => import('@/pages/admin/AdminDashboard'), 'AdminDashboard')
export const VerificationManagement = lazyWithRetry(() => import('@/pages/admin/VerificationManagement'), 'VerificationManagement')
export const RankingWeights = lazyWithRetry(() => import('@/pages/admin/RankingWeights'), 'RankingWeights')
export const ActivityLogs = lazyWithRetry(() => import('@/pages/admin/ActivityLogs'), 'ActivityLogs')
